Change the login process for hdblcm - avoid async task

diff --git a/roles/sap_hana_install/tasks/hana_install.yml b/roles/sap_hana_install/tasks/hana_install.yml
--- a/roles/sap_hana_install/tasks/hana_install.yml
+++ b/roles/sap_hana_install/tasks/hana_install.yml
@@ -11,15 +11,6 @@
     group: root
     mode: '0755'
 
-# Show how to use the workaround:
-- name: Install SAP HANA - Show how to watch the install process in real time
-  ansible.builtin.debug:
-    msg:
-      - 'Once the task "Install SAP HANA" has started, you can use the following command'
-      - 'in a terminal session on {{ inventory_hostname }} to watch the install progress in real time:'
-      - "{{ __sap_hana_install_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
-      - 'Alternatively, you can run the following command on the control node:'
-      - "ssh {{ inventory_hostname }} {{ __sap_hana_install_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
 
 - name: Install SAP HANA - Set fact for the hdblcm verify_signature argument
   ansible.builtin.set_fact:
@@ -39,38 +30,81 @@
     msg: "SAP HANA install command: '{{ __sap_hana_install_hdblcm_command }}'"
   tags: sap_hana_install_hdblcm_commandline
 
+# Show how to use the workaround:
+- name: Install SAP HANA - Show how to watch the install process in real time
+  ansible.builtin.debug:
+    msg:
+      - 'Once the task "Install SAP HANA" has started, you can use the following command'
+      - 'in a terminal session on {{ inventory_hostname }} to watch the install progress in real time:'
+      - "{{ __sap_hana_install_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
+      - 'Alternatively, you can run the following command on the control node:'
+      - "ssh {{ inventory_hostname }} {{ __sap_hana_install_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
+      
+# For asynchronous execution. This function is not possible using morpheus data
+# - name: Install SAP HANA - {{ sap_hana_install_sid }} {{ sap_hana_install_number }}
+#  ansible.builtin.shell: "{{ __sap_hana_install_hdblcm_command }} > /tmp/hdblcm.log 2>&1 &"
+#  register: __sap_hana_install_register_hdblcm_install_async_job
+#  args:
+#    chdir: "{{ __sap_hana_install_fact_hdblcm_path }}"
+#  async: 86400 # Seconds for maximum runtime, set to 24 hours
+#  poll: 0 # Seconds between polls, use 0 to run Ansible Tasks concurrently
+#  changed_when: true
+#  when: not ansible_check_mode
+ 
+#- name: Install SAP HANA - Wait for hdblcm process to exit, poll every 60 seconds
+#  ansible.builtin.shell:
+#    cmd: set -o pipefail && ps -ef | awk '/ hdblcm /&&/ {{ __sap_hana_install_configfile_arg }} /&&!/ awk /{print}'
+#  register: __sap_hana_install_register_pids_sapinst
+#  until: "__sap_hana_install_register_pids_sapinst.stdout | length == 0"
+#  retries: 1440
+#  delay: 60
+#  vars:
+#    __sap_hana_install_configfile_arg: "{{ '--configfile=' + (__sap_hana_install_register_tmpdir.path + '/configfile.cfg') | regex_replace('/', '\\/') }}"
+#  changed_when: false
+
+#- name: Install SAP HANA - Verify if hdblcm process finished successfully
+#  ansible.builtin.async_status:
+#    jid: "{{ __sap_hana_install_register_hdblcm_install_async_job.ansible_job_id }}"
+#  register: __sap_hana_install_register_sapinst
+#  failed_when: __sap_hana_install_register_sapinst.finished != 1 or __sap_hana_install_register_sapinst.rc != 0
+
 - name: Install SAP HANA - {{ sap_hana_install_sid }} {{ sap_hana_install_number }}
-  ansible.builtin.command: "{{ __sap_hana_install_hdblcm_command }}"
-  register: __sap_hana_install_register_hdblcm_install_async_job
+  ansible.builtin.shell: "{{ __sap_hana_install_hdblcm_command }} > /tmp/hdblcm.log 2>&1 & echo $! > /tmp/hdblcm.pid"
   args:
     chdir: "{{ __sap_hana_install_fact_hdblcm_path }}"
-  async: 86400 # Seconds for maximum runtime, set to 24 hours
-  poll: 0 # Seconds between polls, use 0 to run Ansible Tasks concurrently
+  register: __sap_hana_install_register_hdblcm_install
   changed_when: true
   when: not ansible_check_mode
 
-- name: Install SAP HANA - Wait for hdblcm process to exit, poll every 60 seconds
-  ansible.builtin.shell:
-    cmd: set -o pipefail && ps -ef | awk '/ hdblcm /&&/ {{ __sap_hana_install_configfile_arg }} /&&!/ awk /{print}'
-  register: __sap_hana_install_register_pids_sapinst
-  until: "__sap_hana_install_register_pids_sapinst.stdout | length == 0"
-  retries: 1440
-  delay: 60
-  vars:
-    __sap_hana_install_configfile_arg: "{{ '--configfile=' + (__sap_hana_install_register_tmpdir.path + '/configfile.cfg') | regex_replace('/', '\\/') }}"
+# Wait for the process to complete
+- name: Install SAP HANA - Wait for hdblcm process to complete. This can take up to 1 hour to complete.
+  ansible.builtin.shell: |
+    if [ -f /tmp/hdblcm.pid ]; then
+      pid=$(cat /tmp/hdblcm.pid)
+      while ps -p $pid > /dev/null; do
+        sleep 60
+      done
+    else
+      echo "PID file not found. Process may not have started correctly. Check /tmp/hdblcm.log file."
+      exit 1
+    fi
+  register: __monitor_hdblcm_process
+  failed_when: "'PID file not found' in __monitor_hdblcm_process.stdout"
   changed_when: false
 
+# Verify if the installation process finished successfully
 - name: Install SAP HANA - Verify if hdblcm process finished successfully
-  ansible.builtin.async_status:
-    jid: "{{ __sap_hana_install_register_hdblcm_install_async_job.ansible_job_id }}"
+  ansible.builtin.shell:
+    cmd: grep -q "SAP HANA Database System installed" /tmp/hdblcm.log
   register: __sap_hana_install_register_sapinst
-  failed_when: __sap_hana_install_register_sapinst.finished != 1 or __sap_hana_install_register_sapinst.rc != 0
+  failed_when: __sap_hana_install_register_sapinst.rc != 0
 
+# Display the hdblcm return code
 - name: Install SAP HANA - Display the hdblcm return code
   ansible.builtin.debug:
-    msg: "{{ __sap_hana_install_register_sapinst.rc }}"
-
+    msg: "Return code: {{ __sap_hana_install_register_hdblcm_install.rc }}"
+ # Display the hdblcm output
 - name: Install SAP HANA - Display the hdblcm output
   ansible.builtin.debug:
-    msg: "{{ __sap_hana_install_register_sapinst.stdout_lines }}"
+    msg: "{{ __sap_hana_install_register_hdblcm_install.stdout_lines }}"
   when: sap_hana_install_display_unattended_output
